### ISSUE TITLE
create an "AppBar" component

### ISSUE THREAD

**Issue by marko-knoebl** [marko-knoebl/cc-react-components#2]
see https://mui.com/material-ui/ for inspiration

**Comment by marko-knoebl** [comment]
Gute Arbeit! Echt cool, dass du auch gleich ein Dropdown implementiert hast!

Etwas, was ich wohl nicht gut vermittelt habe:

Die Komponenten sollen wiederverwendbar / flexibel sein, sprich in verschiedenen Szenarien eingesetzt werden können.

Die einfachste Verwendung einer AppBar könnte z.B. so aussehen:

```jsx
<AppBar>
  <h1>My Website</h1>
</AppBar>
```

eine Komplexere Verwendung wäre z.B.:

```jsx
<AppBar>
  <h1>My Website</h1>
  <a href="/about">about</a>
  <a href="/home">home</a>
  usw ...
</AppBar>
```

In der Definition in _AppBar.jsx_ soll daher gar nicht so viel stehen, der Inhalt würde vom Verwender angegeben werden!

**Comment by marko-knoebl** [comment]
Und auch richtig cool, dass du ein "Popup-Menü" gemacht hast!

Da würde ich sagen: nimm das vorerst mal wieder raus, und dann schreibe ich dir noch, wie du das anders - flexibler - implementieren kannst!

**Comment by marko-knoebl** [comment]
Wow, die Version jetzt ist richtig cool!

Da hast du mehr implementiert, als ich mir eigentlich gewünscht hätte 👍 👍 👍

Wenn ich mir noch eine Kleinigkeit bezüglich des Codes wünschen könnte, dann wäre das, dass die CSS-Selektoren eindeutiger wären. Momentan ist es so, dass alle _\<a>_-Elemente auf der Seite weiß werden, wenn eine AppBar-Komponente eingebunden ist. Tipp hierzu: Verwende Klassennamen mit Präfixen, z.B. _AppBar__logo_, _AppBar__search_, _AppBar__link_, ...

Wenn du Lust hast, kannst du auch das noch umsetzen, ansonsten ists auch jetzt schon top!

**Comment by AdrianMonemi** [comment]
Danke für deine Komplimente, ich habe diese Woche Nachtschicht und bin gerade arbeiten. Morgen werde ich es bis vor dem Unterricht erledigen, dazu werde ich noch die dropdown liste mit richtige Format imolimentieren, ich habe heute raus gefunden dass die "Hamburger Menu" heißen.
