### ISSUE TITLE
create an "Alert" component

### ISSUE THREAD

**Issue by marko-knoebl** [marko-knoebl/cc-react-components#6]
see https://mui.com/material-ui/ for inspiration

**Comment by marko-knoebl** [comment]
Looks good, nicely done!

Some minor hints concerning the CSS:

You could create a separate general class named `alert`, and more specific classes `alert-error`, `alert-warning`, ... and apply both the general and one of the more specific classes to an element - the `alert-error` etc would only have to change the background-color.

Class names like `icon`, `text` and `title-container` are too generic and could conflict with class names from other components. You could just call them `Alert-icon`, `Alert-text`, `Alert-title-container`.

**Comment by marko-knoebl** [comment]
Another note:

It would be nice if the icon was automatically determined by the type - so if a developer sets `type="error"`, they don't have to set `icon=..."` as well.

**Comment by Kenavm** [comment]
all done :)
